### ISSUE TITLE
info

### ISSUE THREAD

**Issue by DrumClock** [DrumClock/MFG#2]
Hi @thisiskeithb 
( Improve STM32 timer conflict messages #20544)

```
There are more mistakes than before ... I don't know what happened.

You're recycling old files like Conditionals_LCD.h and defines have changed.

This Issue Queue is for Marlin bug reports and development-related issues, and we prefer not to handle user-support questions here. (As noted on this page.) For best results getting help with configuration and troubleshooting, please use the following resources:

MarlinFW.org Marlin Documentation
RepRap.org Marlin Forum
Tom's 3D Forums
Facebook Group "Marlin Firmware"
Facebook Group "Marlin Firmware for 3D Printers"
Marlin Configuration on YouTube
Marlin Discord server. Join link: https://discord.gg/n5NJ59y
```

I use Github desktop software and synchronize my brench with the ustream / bugfix 2.0x branch daily.

![Github](https://user-images.githubusercontent.com/64655979/102920641-5dd03080-448b-11eb-8995-541e7c2fa6d5.png)

How come I have old Marlin modules in my branch?
Either I'm doing something wrong or the Github desktop is not working properly!

**Comment by DrumClock** [comment]
HI @sjasonsmith

```
@DrumClock I just looked at your branch, and all its differences from upstream/bugfix-2.0.x. This is what I looked at:
https://github.com/DrumClock/Marlin/tree/GTR-4EX2

You have MANY merge errors. You are missing MANY upstream changes.

You need to start with a clean version of bugfix-2.0.x and re-apply your configuration to it.

Here is a patch file of all your changes from the upstream branch. If you search you will see that your branch deletes NUM_HARDWARE_TIMERS from timers.h!
DrumClock_changes.zip
```

**how do i use a file DrumClock_changes.patch?**
more is a picture of how I use upstream ..... I don't know if it's the right procedure ....

**Comment by DrumClock** [comment]
HI @sjasonsmith
here is my procedure for using the github surface.

[GitHub.pdf](https://github.com/DrumClock/MFG/files/5735242/GitHub.pdf)

**What I do wrong has MANY merging errors and lacks MANY upstream changes.**

**Comment by sjasonsmith** [comment]
I find it rude that you tagged us into your repo like this. Please use one of the many support forums in Marlin to get help from other people.

People are getting frustrated because you use very rare combinations of features, and expect people to stop and spend their time only helping you.

We do not have the hardware to help you. We do not have the knowledge to help you.

If you use rare or unfinished features, you must be ready to fix problems yourself or a hire a developer to do it for you.

**Comment by sjasonsmith** [comment]
Please do not reply here. We have both unsubscribed from notifications and will not see it.
